/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cmc.gateway.domain.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AppDomain service. Represents a row in the &quot;GW_AppDomain&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cmc.gateway.domain.model.impl.AppDomainModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cmc.gateway.domain.model.impl.AppDomainImpl}.
 * </p>
 *
 * @author Richard Nguyen
 * @see AppDomain
 * @see com.cmc.gateway.domain.model.impl.AppDomainImpl
 * @see com.cmc.gateway.domain.model.impl.AppDomainModelImpl
 * @generated
 */
public interface AppDomainModel extends BaseModel<AppDomain> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a app domain model instance should use the {@link AppDomain} interface instead.
	 */

	/**
	 * Returns the primary key of this app domain.
	 *
	 * @return the primary key of this app domain
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this app domain.
	 *
	 * @param primaryKey the primary key of this app domain
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the domain ID of this app domain.
	 *
	 * @return the domain ID of this app domain
	 */
	public long getDomainId();

	/**
	 * Sets the domain ID of this app domain.
	 *
	 * @param domainId the domain ID of this app domain
	 */
	public void setDomainId(long domainId);

	/**
	 * Returns the group ID of this app domain.
	 *
	 * @return the group ID of this app domain
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this app domain.
	 *
	 * @param groupId the group ID of this app domain
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this app domain.
	 *
	 * @return the company ID of this app domain
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this app domain.
	 *
	 * @param companyId the company ID of this app domain
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this app domain.
	 *
	 * @return the user ID of this app domain
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this app domain.
	 *
	 * @param userId the user ID of this app domain
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this app domain.
	 *
	 * @return the user uuid of this app domain
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this app domain.
	 *
	 * @param userUuid the user uuid of this app domain
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this app domain.
	 *
	 * @return the create date of this app domain
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this app domain.
	 *
	 * @param createDate the create date of this app domain
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this app domain.
	 *
	 * @return the modified date of this app domain
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this app domain.
	 *
	 * @param modifiedDate the modified date of this app domain
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the type of this app domain.
	 *
	 * @return the type of this app domain
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this app domain.
	 *
	 * @param type the type of this app domain
	 */
	public void setType(String type);

	/**
	 * Returns the code of this app domain.
	 *
	 * @return the code of this app domain
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this app domain.
	 *
	 * @param code the code of this app domain
	 */
	public void setCode(String code);

	/**
	 * Returns the title of this app domain.
	 *
	 * @return the title of this app domain
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this app domain.
	 *
	 * @param title the title of this app domain
	 */
	public void setTitle(String title);

	/**
	 * Returns the value of this app domain.
	 *
	 * @return the value of this app domain
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this app domain.
	 *
	 * @param value the value of this app domain
	 */
	public void setValue(String value);

	/**
	 * Returns the default value of this app domain.
	 *
	 * @return the default value of this app domain
	 */
	public boolean getDefaultValue();

	/**
	 * Returns <code>true</code> if this app domain is default value.
	 *
	 * @return <code>true</code> if this app domain is default value; <code>false</code> otherwise
	 */
	public boolean isDefaultValue();

	/**
	 * Sets whether this app domain is default value.
	 *
	 * @param defaultValue the default value of this app domain
	 */
	public void setDefaultValue(boolean defaultValue);

	/**
	 * Returns the description of this app domain.
	 *
	 * @return the description of this app domain
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this app domain.
	 *
	 * @param description the description of this app domain
	 */
	public void setDescription(String description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(AppDomain appDomain);

	public int hashCode();

	public CacheModel<AppDomain> toCacheModel();

	public AppDomain toEscapedModel();

	public String toString();

	public String toXmlString();
}