/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cmc.gateway.domain.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CommandEntry service. Represents a row in the &quot;GW_CommandEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cmc.gateway.domain.model.impl.CommandEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cmc.gateway.domain.model.impl.CommandEntryImpl}.
 * </p>
 *
 * @author Richard Nguyen
 * @see CommandEntry
 * @see com.cmc.gateway.domain.model.impl.CommandEntryImpl
 * @see com.cmc.gateway.domain.model.impl.CommandEntryModelImpl
 * @generated
 */
public interface CommandEntryModel extends BaseModel<CommandEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a command entry model instance should use the {@link CommandEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this command entry.
	 *
	 * @return the primary key of this command entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this command entry.
	 *
	 * @param primaryKey the primary key of this command entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the command ID of this command entry.
	 *
	 * @return the command ID of this command entry
	 */
	public long getCommandId();

	/**
	 * Sets the command ID of this command entry.
	 *
	 * @param commandId the command ID of this command entry
	 */
	public void setCommandId(long commandId);

	/**
	 * Returns the group ID of this command entry.
	 *
	 * @return the group ID of this command entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this command entry.
	 *
	 * @param groupId the group ID of this command entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this command entry.
	 *
	 * @return the company ID of this command entry
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this command entry.
	 *
	 * @param companyId the company ID of this command entry
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this command entry.
	 *
	 * @return the user ID of this command entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this command entry.
	 *
	 * @param userId the user ID of this command entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this command entry.
	 *
	 * @return the user uuid of this command entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this command entry.
	 *
	 * @param userUuid the user uuid of this command entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this command entry.
	 *
	 * @return the create date of this command entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this command entry.
	 *
	 * @param createDate the create date of this command entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this command entry.
	 *
	 * @return the modified date of this command entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this command entry.
	 *
	 * @param modifiedDate the modified date of this command entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the provisioning type of this command entry.
	 *
	 * @return the provisioning type of this command entry
	 */
	@AutoEscape
	public String getProvisioningType();

	/**
	 * Sets the provisioning type of this command entry.
	 *
	 * @param provisioningType the provisioning type of this command entry
	 */
	public void setProvisioningType(String provisioningType);

	/**
	 * Returns the code of this command entry.
	 *
	 * @return the code of this command entry
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this command entry.
	 *
	 * @param code the code of this command entry
	 */
	public void setCode(String code);

	/**
	 * Returns the title of this command entry.
	 *
	 * @return the title of this command entry
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this command entry.
	 *
	 * @param title the title of this command entry
	 */
	public void setTitle(String title);

	/**
	 * Returns the priority of this command entry.
	 *
	 * @return the priority of this command entry
	 */
	public int getPriority();

	/**
	 * Sets the priority of this command entry.
	 *
	 * @param priority the priority of this command entry
	 */
	public void setPriority(int priority);

	/**
	 * Returns the timeout of this command entry.
	 *
	 * @return the timeout of this command entry
	 */
	public int getTimeout();

	/**
	 * Sets the timeout of this command entry.
	 *
	 * @param timeout the timeout of this command entry
	 */
	public void setTimeout(int timeout);

	/**
	 * Returns the retry enable of this command entry.
	 *
	 * @return the retry enable of this command entry
	 */
	public boolean getRetryEnable();

	/**
	 * Returns <code>true</code> if this command entry is retry enable.
	 *
	 * @return <code>true</code> if this command entry is retry enable; <code>false</code> otherwise
	 */
	public boolean isRetryEnable();

	/**
	 * Sets whether this command entry is retry enable.
	 *
	 * @param retryEnable the retry enable of this command entry
	 */
	public void setRetryEnable(boolean retryEnable);

	/**
	 * Returns the max retry of this command entry.
	 *
	 * @return the max retry of this command entry
	 */
	public int getMaxRetry();

	/**
	 * Sets the max retry of this command entry.
	 *
	 * @param maxRetry the max retry of this command entry
	 */
	public void setMaxRetry(int maxRetry);

	/**
	 * Returns the log enable of this command entry.
	 *
	 * @return the log enable of this command entry
	 */
	public boolean getLogEnable();

	/**
	 * Returns <code>true</code> if this command entry is log enable.
	 *
	 * @return <code>true</code> if this command entry is log enable; <code>false</code> otherwise
	 */
	public boolean isLogEnable();

	/**
	 * Sets whether this command entry is log enable.
	 *
	 * @param logEnable the log enable of this command entry
	 */
	public void setLogEnable(boolean logEnable);

	/**
	 * Returns the properties of this command entry.
	 *
	 * @return the properties of this command entry
	 */
	@AutoEscape
	public String getProperties();

	/**
	 * Sets the properties of this command entry.
	 *
	 * @param properties the properties of this command entry
	 */
	public void setProperties(String properties);

	/**
	 * Returns the status of this command entry.
	 *
	 * @return the status of this command entry
	 */
	public int getStatus();

	/**
	 * Sets the status of this command entry.
	 *
	 * @param status the status of this command entry
	 */
	public void setStatus(int status);

	/**
	 * Returns the description of this command entry.
	 *
	 * @return the description of this command entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this command entry.
	 *
	 * @param description the description of this command entry
	 */
	public void setDescription(String description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(CommandEntry commandEntry);

	public int hashCode();

	public CacheModel<CommandEntry> toCacheModel();

	public CommandEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}