/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cmc.gateway.domain.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProductRoute service. Represents a row in the &quot;GW_ProductRoute&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cmc.gateway.domain.model.impl.ProductRouteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cmc.gateway.domain.model.impl.ProductRouteImpl}.
 * </p>
 *
 * @author Richard Nguyen
 * @see ProductRoute
 * @see com.cmc.gateway.domain.model.impl.ProductRouteImpl
 * @see com.cmc.gateway.domain.model.impl.ProductRouteModelImpl
 * @generated
 */
public interface ProductRouteModel extends BaseModel<ProductRoute> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product route model instance should use the {@link ProductRoute} interface instead.
	 */

	/**
	 * Returns the primary key of this product route.
	 *
	 * @return the primary key of this product route
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product route.
	 *
	 * @param primaryKey the primary key of this product route
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the route ID of this product route.
	 *
	 * @return the route ID of this product route
	 */
	public long getRouteId();

	/**
	 * Sets the route ID of this product route.
	 *
	 * @param routeId the route ID of this product route
	 */
	public void setRouteId(long routeId);

	/**
	 * Returns the group ID of this product route.
	 *
	 * @return the group ID of this product route
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this product route.
	 *
	 * @param groupId the group ID of this product route
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this product route.
	 *
	 * @return the company ID of this product route
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this product route.
	 *
	 * @param companyId the company ID of this product route
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this product route.
	 *
	 * @return the user ID of this product route
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this product route.
	 *
	 * @param userId the user ID of this product route
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this product route.
	 *
	 * @return the user uuid of this product route
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this product route.
	 *
	 * @param userUuid the user uuid of this product route
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this product route.
	 *
	 * @return the create date of this product route
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this product route.
	 *
	 * @param createDate the create date of this product route
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this product route.
	 *
	 * @return the modified date of this product route
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this product route.
	 *
	 * @param modifiedDate the modified date of this product route
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the channel of this product route.
	 *
	 * @return the channel of this product route
	 */
	@AutoEscape
	public String getChannel();

	/**
	 * Sets the channel of this product route.
	 *
	 * @param channel the channel of this product route
	 */
	public void setChannel(String channel);

	/**
	 * Returns the service address of this product route.
	 *
	 * @return the service address of this product route
	 */
	@AutoEscape
	public String getServiceAddress();

	/**
	 * Sets the service address of this product route.
	 *
	 * @param serviceAddress the service address of this product route
	 */
	public void setServiceAddress(String serviceAddress);

	/**
	 * Returns the keyword of this product route.
	 *
	 * @return the keyword of this product route
	 */
	@AutoEscape
	public String getKeyword();

	/**
	 * Sets the keyword of this product route.
	 *
	 * @param keyword the keyword of this product route
	 */
	public void setKeyword(String keyword);

	/**
	 * Returns the open time of this product route.
	 *
	 * @return the open time of this product route
	 */
	@AutoEscape
	public String getOpenTime();

	/**
	 * Sets the open time of this product route.
	 *
	 * @param openTime the open time of this product route
	 */
	public void setOpenTime(String openTime);

	/**
	 * Returns the closed time of this product route.
	 *
	 * @return the closed time of this product route
	 */
	@AutoEscape
	public String getClosedTime();

	/**
	 * Sets the closed time of this product route.
	 *
	 * @param closedTime the closed time of this product route
	 */
	public void setClosedTime(String closedTime);

	/**
	 * Returns the check balance of this product route.
	 *
	 * @return the check balance of this product route
	 */
	public boolean getCheckBalance();

	/**
	 * Returns <code>true</code> if this product route is check balance.
	 *
	 * @return <code>true</code> if this product route is check balance; <code>false</code> otherwise
	 */
	public boolean isCheckBalance();

	/**
	 * Sets whether this product route is check balance.
	 *
	 * @param checkBalance the check balance of this product route
	 */
	public void setCheckBalance(boolean checkBalance);

	/**
	 * Returns the sms min params of this product route.
	 *
	 * @return the sms min params of this product route
	 */
	public int getSmsMinParams();

	/**
	 * Sets the sms min params of this product route.
	 *
	 * @param smsMinParams the sms min params of this product route
	 */
	public void setSmsMinParams(int smsMinParams);

	/**
	 * Returns the sms max params of this product route.
	 *
	 * @return the sms max params of this product route
	 */
	public int getSmsMaxParams();

	/**
	 * Sets the sms max params of this product route.
	 *
	 * @param smsMaxParams the sms max params of this product route
	 */
	public void setSmsMaxParams(int smsMaxParams);

	/**
	 * Returns the action type of this product route.
	 *
	 * @return the action type of this product route
	 */
	@AutoEscape
	public String getActionType();

	/**
	 * Sets the action type of this product route.
	 *
	 * @param actionType the action type of this product route
	 */
	public void setActionType(String actionType);

	/**
	 * Returns the product ID of this product route.
	 *
	 * @return the product ID of this product route
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this product route.
	 *
	 * @param productId the product ID of this product route
	 */
	public void setProductId(long productId);

	/**
	 * Returns the campaign ID of this product route.
	 *
	 * @return the campaign ID of this product route
	 */
	public long getCampaignId();

	/**
	 * Sets the campaign ID of this product route.
	 *
	 * @param campaignId the campaign ID of this product route
	 */
	public void setCampaignId(long campaignId);

	/**
	 * Returns the language ID of this product route.
	 *
	 * @return the language ID of this product route
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this product route.
	 *
	 * @param languageId the language ID of this product route
	 */
	public void setLanguageId(String languageId);

	/**
	 * Returns the synchronous of this product route.
	 *
	 * @return the synchronous of this product route
	 */
	public boolean getSynchronous();

	/**
	 * Returns <code>true</code> if this product route is synchronous.
	 *
	 * @return <code>true</code> if this product route is synchronous; <code>false</code> otherwise
	 */
	public boolean isSynchronous();

	/**
	 * Sets whether this product route is synchronous.
	 *
	 * @param synchronous the synchronous of this product route
	 */
	public void setSynchronous(boolean synchronous);

	/**
	 * Returns the create order of this product route.
	 *
	 * @return the create order of this product route
	 */
	public boolean getCreateOrder();

	/**
	 * Returns <code>true</code> if this product route is create order.
	 *
	 * @return <code>true</code> if this product route is create order; <code>false</code> otherwise
	 */
	public boolean isCreateOrder();

	/**
	 * Sets whether this product route is create order.
	 *
	 * @param createOrder the create order of this product route
	 */
	public void setCreateOrder(boolean createOrder);

	/**
	 * Returns the timeout of this product route.
	 *
	 * @return the timeout of this product route
	 */
	public int getTimeout();

	/**
	 * Sets the timeout of this product route.
	 *
	 * @param timeout the timeout of this product route
	 */
	public void setTimeout(int timeout);

	/**
	 * Returns the max register daily of this product route.
	 *
	 * @return the max register daily of this product route
	 */
	public int getMaxRegisterDaily();

	/**
	 * Sets the max register daily of this product route.
	 *
	 * @param maxRegisterDaily the max register daily of this product route
	 */
	public void setMaxRegisterDaily(int maxRegisterDaily);

	/**
	 * Returns the duplicate scan of this product route.
	 *
	 * @return the duplicate scan of this product route
	 */
	public int getDuplicateScan();

	/**
	 * Sets the duplicate scan of this product route.
	 *
	 * @param duplicateScan the duplicate scan of this product route
	 */
	public void setDuplicateScan(int duplicateScan);

	/**
	 * Returns the check spam of this product route.
	 *
	 * @return the check spam of this product route
	 */
	public boolean getCheckSpam();

	/**
	 * Returns <code>true</code> if this product route is check spam.
	 *
	 * @return <code>true</code> if this product route is check spam; <code>false</code> otherwise
	 */
	public boolean isCheckSpam();

	/**
	 * Sets whether this product route is check spam.
	 *
	 * @param checkSpam the check spam of this product route
	 */
	public void setCheckSpam(boolean checkSpam);

	/**
	 * Returns the fraud times of this product route.
	 *
	 * @return the fraud times of this product route
	 */
	public int getFraudTimes();

	/**
	 * Sets the fraud times of this product route.
	 *
	 * @param fraudTimes the fraud times of this product route
	 */
	public void setFraudTimes(int fraudTimes);

	/**
	 * Returns the fraud period of this product route.
	 *
	 * @return the fraud period of this product route
	 */
	public int getFraudPeriod();

	/**
	 * Sets the fraud period of this product route.
	 *
	 * @param fraudPeriod the fraud period of this product route
	 */
	public void setFraudPeriod(int fraudPeriod);

	/**
	 * Returns the fraud unit of this product route.
	 *
	 * @return the fraud unit of this product route
	 */
	@AutoEscape
	public String getFraudUnit();

	/**
	 * Sets the fraud unit of this product route.
	 *
	 * @param fraudUnit the fraud unit of this product route
	 */
	public void setFraudUnit(String fraudUnit);

	/**
	 * Returns the reject unit of this product route.
	 *
	 * @return the reject unit of this product route
	 */
	@AutoEscape
	public String getRejectUnit();

	/**
	 * Sets the reject unit of this product route.
	 *
	 * @param rejectUnit the reject unit of this product route
	 */
	public void setRejectUnit(String rejectUnit);

	/**
	 * Returns the reject period of this product route.
	 *
	 * @return the reject period of this product route
	 */
	public int getRejectPeriod();

	/**
	 * Sets the reject period of this product route.
	 *
	 * @param rejectPeriod the reject period of this product route
	 */
	public void setRejectPeriod(int rejectPeriod);

	/**
	 * Returns the base charge enable of this product route.
	 *
	 * @return the base charge enable of this product route
	 */
	public boolean getBaseChargeEnable();

	/**
	 * Returns <code>true</code> if this product route is base charge enable.
	 *
	 * @return <code>true</code> if this product route is base charge enable; <code>false</code> otherwise
	 */
	public boolean isBaseChargeEnable();

	/**
	 * Sets whether this product route is base charge enable.
	 *
	 * @param baseChargeEnable the base charge enable of this product route
	 */
	public void setBaseChargeEnable(boolean baseChargeEnable);

	/**
	 * Returns the charging amount of this product route.
	 *
	 * @return the charging amount of this product route
	 */
	public double getChargingAmount();

	/**
	 * Sets the charging amount of this product route.
	 *
	 * @param chargingAmount the charging amount of this product route
	 */
	public void setChargingAmount(double chargingAmount);

	/**
	 * Returns the notify owner of this product route.
	 *
	 * @return the notify owner of this product route
	 */
	public boolean getNotifyOwner();

	/**
	 * Returns <code>true</code> if this product route is notify owner.
	 *
	 * @return <code>true</code> if this product route is notify owner; <code>false</code> otherwise
	 */
	public boolean isNotifyOwner();

	/**
	 * Sets whether this product route is notify owner.
	 *
	 * @param notifyOwner the notify owner of this product route
	 */
	public void setNotifyOwner(boolean notifyOwner);

	/**
	 * Returns the notify deliver of this product route.
	 *
	 * @return the notify deliver of this product route
	 */
	public boolean getNotifyDeliver();

	/**
	 * Returns <code>true</code> if this product route is notify deliver.
	 *
	 * @return <code>true</code> if this product route is notify deliver; <code>false</code> otherwise
	 */
	public boolean isNotifyDeliver();

	/**
	 * Sets whether this product route is notify deliver.
	 *
	 * @param notifyDeliver the notify deliver of this product route
	 */
	public void setNotifyDeliver(boolean notifyDeliver);

	/**
	 * Returns the send advertising of this product route.
	 *
	 * @return the send advertising of this product route
	 */
	public boolean getSendAdvertising();

	/**
	 * Returns <code>true</code> if this product route is send advertising.
	 *
	 * @return <code>true</code> if this product route is send advertising; <code>false</code> otherwise
	 */
	public boolean isSendAdvertising();

	/**
	 * Sets whether this product route is send advertising.
	 *
	 * @param sendAdvertising the send advertising of this product route
	 */
	public void setSendAdvertising(boolean sendAdvertising);

	/**
	 * Returns the check promotion of this product route.
	 *
	 * @return the check promotion of this product route
	 */
	public boolean getCheckPromotion();

	/**
	 * Returns <code>true</code> if this product route is check promotion.
	 *
	 * @return <code>true</code> if this product route is check promotion; <code>false</code> otherwise
	 */
	public boolean isCheckPromotion();

	/**
	 * Sets whether this product route is check promotion.
	 *
	 * @param checkPromotion the check promotion of this product route
	 */
	public void setCheckPromotion(boolean checkPromotion);

	/**
	 * Returns the topup enable of this product route.
	 *
	 * @return the topup enable of this product route
	 */
	public boolean getTopupEnable();

	/**
	 * Returns <code>true</code> if this product route is topup enable.
	 *
	 * @return <code>true</code> if this product route is topup enable; <code>false</code> otherwise
	 */
	public boolean isTopupEnable();

	/**
	 * Sets whether this product route is topup enable.
	 *
	 * @param topupEnable the topup enable of this product route
	 */
	public void setTopupEnable(boolean topupEnable);

	/**
	 * Returns the properties of this product route.
	 *
	 * @return the properties of this product route
	 */
	@AutoEscape
	public String getProperties();

	/**
	 * Sets the properties of this product route.
	 *
	 * @param properties the properties of this product route
	 */
	public void setProperties(String properties);

	/**
	 * Returns the queue name of this product route.
	 *
	 * @return the queue name of this product route
	 */
	@AutoEscape
	public String getQueueName();

	/**
	 * Sets the queue name of this product route.
	 *
	 * @param queueName the queue name of this product route
	 */
	public void setQueueName(String queueName);

	/**
	 * Returns the process class of this product route.
	 *
	 * @return the process class of this product route
	 */
	@AutoEscape
	public String getProcessClass();

	/**
	 * Sets the process class of this product route.
	 *
	 * @param processClass the process class of this product route
	 */
	public void setProcessClass(String processClass);

	/**
	 * Returns the process method of this product route.
	 *
	 * @return the process method of this product route
	 */
	@AutoEscape
	public String getProcessMethod();

	/**
	 * Sets the process method of this product route.
	 *
	 * @param processMethod the process method of this product route
	 */
	public void setProcessMethod(String processMethod);

	/**
	 * Returns the status of this product route.
	 *
	 * @return the status of this product route
	 */
	public int getStatus();

	/**
	 * Sets the status of this product route.
	 *
	 * @param status the status of this product route
	 */
	public void setStatus(int status);

	/**
	 * Returns the start date of this product route.
	 *
	 * @return the start date of this product route
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this product route.
	 *
	 * @param startDate the start date of this product route
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the expiration date of this product route.
	 *
	 * @return the expiration date of this product route
	 */
	public Date getExpirationDate();

	/**
	 * Sets the expiration date of this product route.
	 *
	 * @param expirationDate the expiration date of this product route
	 */
	public void setExpirationDate(Date expirationDate);

	/**
	 * Returns the description of this product route.
	 *
	 * @return the description of this product route
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this product route.
	 *
	 * @param description the description of this product route
	 */
	public void setDescription(String description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ProductRoute productRoute);

	public int hashCode();

	public CacheModel<ProductRoute> toCacheModel();

	public ProductRoute toEscapedModel();

	public String toString();

	public String toXmlString();
}