/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cmc.gateway.domain.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProductEntry service. Represents a row in the &quot;GW_ProductEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cmc.gateway.domain.model.impl.ProductEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cmc.gateway.domain.model.impl.ProductEntryImpl}.
 * </p>
 *
 * @author Richard Nguyen
 * @see ProductEntry
 * @see com.cmc.gateway.domain.model.impl.ProductEntryImpl
 * @see com.cmc.gateway.domain.model.impl.ProductEntryModelImpl
 * @generated
 */
public interface ProductEntryModel extends BaseModel<ProductEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product entry model instance should use the {@link ProductEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this product entry.
	 *
	 * @return the primary key of this product entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product entry.
	 *
	 * @param primaryKey the primary key of this product entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the product ID of this product entry.
	 *
	 * @return the product ID of this product entry
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this product entry.
	 *
	 * @param productId the product ID of this product entry
	 */
	public void setProductId(long productId);

	/**
	 * Returns the group ID of this product entry.
	 *
	 * @return the group ID of this product entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this product entry.
	 *
	 * @param groupId the group ID of this product entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this product entry.
	 *
	 * @return the company ID of this product entry
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this product entry.
	 *
	 * @param companyId the company ID of this product entry
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this product entry.
	 *
	 * @return the user ID of this product entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this product entry.
	 *
	 * @param userId the user ID of this product entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this product entry.
	 *
	 * @return the user uuid of this product entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this product entry.
	 *
	 * @param userUuid the user uuid of this product entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this product entry.
	 *
	 * @return the create date of this product entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this product entry.
	 *
	 * @param createDate the create date of this product entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this product entry.
	 *
	 * @return the modified date of this product entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this product entry.
	 *
	 * @param modifiedDate the modified date of this product entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the category ID of this product entry.
	 *
	 * @return the category ID of this product entry
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this product entry.
	 *
	 * @param categoryId the category ID of this product entry
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the product type of this product entry.
	 *
	 * @return the product type of this product entry
	 */
	@AutoEscape
	public String getProductType();

	/**
	 * Sets the product type of this product entry.
	 *
	 * @param productType the product type of this product entry
	 */
	public void setProductType(String productType);

	/**
	 * Returns the code of this product entry.
	 *
	 * @return the code of this product entry
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this product entry.
	 *
	 * @param code the code of this product entry
	 */
	public void setCode(String code);

	/**
	 * Returns the title of this product entry.
	 *
	 * @return the title of this product entry
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this product entry.
	 *
	 * @param title the title of this product entry
	 */
	public void setTitle(String title);

	/**
	 * Returns the sku of this product entry.
	 *
	 * @return the sku of this product entry
	 */
	@AutoEscape
	public String getSku();

	/**
	 * Sets the sku of this product entry.
	 *
	 * @param sku the sku of this product entry
	 */
	public void setSku(String sku);

	/**
	 * Returns the price of this product entry.
	 *
	 * @return the price of this product entry
	 */
	public double getPrice();

	/**
	 * Sets the price of this product entry.
	 *
	 * @param price the price of this product entry
	 */
	public void setPrice(double price);

	/**
	 * Returns the subscriber types of this product entry.
	 *
	 * @return the subscriber types of this product entry
	 */
	@AutoEscape
	public String getSubscriberTypes();

	/**
	 * Sets the subscriber types of this product entry.
	 *
	 * @param subscriberTypes the subscriber types of this product entry
	 */
	public void setSubscriberTypes(String subscriberTypes);

	/**
	 * Returns the term of use of this product entry.
	 *
	 * @return the term of use of this product entry
	 */
	public boolean getTermOfUse();

	/**
	 * Returns <code>true</code> if this product entry is term of use.
	 *
	 * @return <code>true</code> if this product entry is term of use; <code>false</code> otherwise
	 */
	public boolean isTermOfUse();

	/**
	 * Sets whether this product entry is term of use.
	 *
	 * @param termOfUse the term of use of this product entry
	 */
	public void setTermOfUse(boolean termOfUse);

	/**
	 * Returns the term period of this product entry.
	 *
	 * @return the term period of this product entry
	 */
	public int getTermPeriod();

	/**
	 * Sets the term period of this product entry.
	 *
	 * @param termPeriod the term period of this product entry
	 */
	public void setTermPeriod(int termPeriod);

	/**
	 * Returns the term unit of this product entry.
	 *
	 * @return the term unit of this product entry
	 */
	@AutoEscape
	public String getTermUnit();

	/**
	 * Sets the term unit of this product entry.
	 *
	 * @param termUnit the term unit of this product entry
	 */
	public void setTermUnit(String termUnit);

	/**
	 * Returns the subscription of this product entry.
	 *
	 * @return the subscription of this product entry
	 */
	public boolean getSubscription();

	/**
	 * Returns <code>true</code> if this product entry is subscription.
	 *
	 * @return <code>true</code> if this product entry is subscription; <code>false</code> otherwise
	 */
	public boolean isSubscription();

	/**
	 * Sets whether this product entry is subscription.
	 *
	 * @param subscription the subscription of this product entry
	 */
	public void setSubscription(boolean subscription);

	/**
	 * Returns the subscription unit of this product entry.
	 *
	 * @return the subscription unit of this product entry
	 */
	@AutoEscape
	public String getSubscriptionUnit();

	/**
	 * Sets the subscription unit of this product entry.
	 *
	 * @param subscriptionUnit the subscription unit of this product entry
	 */
	public void setSubscriptionUnit(String subscriptionUnit);

	/**
	 * Returns the subscription period of this product entry.
	 *
	 * @return the subscription period of this product entry
	 */
	public int getSubscriptionPeriod();

	/**
	 * Sets the subscription period of this product entry.
	 *
	 * @param subscriptionPeriod the subscription period of this product entry
	 */
	public void setSubscriptionPeriod(int subscriptionPeriod);

	/**
	 * Returns the grace period of this product entry.
	 *
	 * @return the grace period of this product entry
	 */
	public int getGracePeriod();

	/**
	 * Sets the grace period of this product entry.
	 *
	 * @param gracePeriod the grace period of this product entry
	 */
	public void setGracePeriod(int gracePeriod);

	/**
	 * Returns the grace unit of this product entry.
	 *
	 * @return the grace unit of this product entry
	 */
	@AutoEscape
	public String getGraceUnit();

	/**
	 * Sets the grace unit of this product entry.
	 *
	 * @param graceUnit the grace unit of this product entry
	 */
	public void setGraceUnit(String graceUnit);

	/**
	 * Returns the status of this product entry.
	 *
	 * @return the status of this product entry
	 */
	public int getStatus();

	/**
	 * Sets the status of this product entry.
	 *
	 * @param status the status of this product entry
	 */
	public void setStatus(int status);

	/**
	 * Returns the description of this product entry.
	 *
	 * @return the description of this product entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this product entry.
	 *
	 * @param description the description of this product entry
	 */
	public void setDescription(String description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ProductEntry productEntry);

	public int hashCode();

	public CacheModel<ProductEntry> toCacheModel();

	public ProductEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}