/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cmc.gateway.domain.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProductAction service. Represents a row in the &quot;GW_ProductAction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cmc.gateway.domain.model.impl.ProductActionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cmc.gateway.domain.model.impl.ProductActionImpl}.
 * </p>
 *
 * @author Richard Nguyen
 * @see ProductAction
 * @see com.cmc.gateway.domain.model.impl.ProductActionImpl
 * @see com.cmc.gateway.domain.model.impl.ProductActionModelImpl
 * @generated
 */
public interface ProductActionModel extends BaseModel<ProductAction> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product action model instance should use the {@link ProductAction} interface instead.
	 */

	/**
	 * Returns the primary key of this product action.
	 *
	 * @return the primary key of this product action
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product action.
	 *
	 * @param primaryKey the primary key of this product action
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the action ID of this product action.
	 *
	 * @return the action ID of this product action
	 */
	public long getActionId();

	/**
	 * Sets the action ID of this product action.
	 *
	 * @param actionId the action ID of this product action
	 */
	public void setActionId(long actionId);

	/**
	 * Returns the group ID of this product action.
	 *
	 * @return the group ID of this product action
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this product action.
	 *
	 * @param groupId the group ID of this product action
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this product action.
	 *
	 * @return the company ID of this product action
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this product action.
	 *
	 * @param companyId the company ID of this product action
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this product action.
	 *
	 * @return the user ID of this product action
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this product action.
	 *
	 * @param userId the user ID of this product action
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this product action.
	 *
	 * @return the user uuid of this product action
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this product action.
	 *
	 * @param userUuid the user uuid of this product action
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this product action.
	 *
	 * @return the create date of this product action
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this product action.
	 *
	 * @param createDate the create date of this product action
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this product action.
	 *
	 * @return the modified date of this product action
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this product action.
	 *
	 * @param modifiedDate the modified date of this product action
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the action type of this product action.
	 *
	 * @return the action type of this product action
	 */
	@AutoEscape
	public String getActionType();

	/**
	 * Sets the action type of this product action.
	 *
	 * @param actionType the action type of this product action
	 */
	public void setActionType(String actionType);

	/**
	 * Returns the subscriber type of this product action.
	 *
	 * @return the subscriber type of this product action
	 */
	public int getSubscriberType();

	/**
	 * Sets the subscriber type of this product action.
	 *
	 * @param subscriberType the subscriber type of this product action
	 */
	public void setSubscriberType(int subscriberType);

	/**
	 * Returns the product ID of this product action.
	 *
	 * @return the product ID of this product action
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this product action.
	 *
	 * @param productId the product ID of this product action
	 */
	public void setProductId(long productId);

	/**
	 * Returns the balance type of this product action.
	 *
	 * @return the balance type of this product action
	 */
	@AutoEscape
	public String getBalanceType();

	/**
	 * Sets the balance type of this product action.
	 *
	 * @param balanceType the balance type of this product action
	 */
	public void setBalanceType(String balanceType);

	/**
	 * Returns the command ID of this product action.
	 *
	 * @return the command ID of this product action
	 */
	public long getCommandId();

	/**
	 * Sets the command ID of this product action.
	 *
	 * @param commandId the command ID of this product action
	 */
	public void setCommandId(long commandId);

	/**
	 * Returns the description of this product action.
	 *
	 * @return the description of this product action
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this product action.
	 *
	 * @param description the description of this product action
	 */
	public void setDescription(String description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ProductAction productAction);

	public int hashCode();

	public CacheModel<ProductAction> toCacheModel();

	public ProductAction toEscapedModel();

	public String toString();

	public String toXmlString();
}