/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cmc.gateway.domain.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProductMessage service. Represents a row in the &quot;GW_ProductMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cmc.gateway.domain.model.impl.ProductMessageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cmc.gateway.domain.model.impl.ProductMessageImpl}.
 * </p>
 *
 * @author Richard Nguyen
 * @see ProductMessage
 * @see com.cmc.gateway.domain.model.impl.ProductMessageImpl
 * @see com.cmc.gateway.domain.model.impl.ProductMessageModelImpl
 * @generated
 */
public interface ProductMessageModel extends BaseModel<ProductMessage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product message model instance should use the {@link ProductMessage} interface instead.
	 */

	/**
	 * Returns the primary key of this product message.
	 *
	 * @return the primary key of this product message
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product message.
	 *
	 * @param primaryKey the primary key of this product message
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the message ID of this product message.
	 *
	 * @return the message ID of this product message
	 */
	public long getMessageId();

	/**
	 * Sets the message ID of this product message.
	 *
	 * @param messageId the message ID of this product message
	 */
	public void setMessageId(long messageId);

	/**
	 * Returns the group ID of this product message.
	 *
	 * @return the group ID of this product message
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this product message.
	 *
	 * @param groupId the group ID of this product message
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this product message.
	 *
	 * @return the company ID of this product message
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this product message.
	 *
	 * @param companyId the company ID of this product message
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this product message.
	 *
	 * @return the user ID of this product message
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this product message.
	 *
	 * @param userId the user ID of this product message
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this product message.
	 *
	 * @return the user uuid of this product message
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this product message.
	 *
	 * @param userUuid the user uuid of this product message
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this product message.
	 *
	 * @return the create date of this product message
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this product message.
	 *
	 * @param createDate the create date of this product message
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this product message.
	 *
	 * @return the modified date of this product message
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this product message.
	 *
	 * @param modifiedDate the modified date of this product message
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the product ID of this product message.
	 *
	 * @return the product ID of this product message
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this product message.
	 *
	 * @param productId the product ID of this product message
	 */
	public void setProductId(long productId);

	/**
	 * Returns the action type of this product message.
	 *
	 * @return the action type of this product message
	 */
	@AutoEscape
	public String getActionType();

	/**
	 * Sets the action type of this product message.
	 *
	 * @param actionType the action type of this product message
	 */
	public void setActionType(String actionType);

	/**
	 * Returns the channel of this product message.
	 *
	 * @return the channel of this product message
	 */
	@AutoEscape
	public String getChannel();

	/**
	 * Sets the channel of this product message.
	 *
	 * @param channel the channel of this product message
	 */
	public void setChannel(String channel);

	/**
	 * Returns the cause of this product message.
	 *
	 * @return the cause of this product message
	 */
	@AutoEscape
	public String getCause();

	/**
	 * Sets the cause of this product message.
	 *
	 * @param cause the cause of this product message
	 */
	public void setCause(String cause);

	/**
	 * Returns the language ID of this product message.
	 *
	 * @return the language ID of this product message
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this product message.
	 *
	 * @param languageId the language ID of this product message
	 */
	public void setLanguageId(String languageId);

	/**
	 * Returns the cause value of this product message.
	 *
	 * @return the cause value of this product message
	 */
	public int getCauseValue();

	/**
	 * Sets the cause value of this product message.
	 *
	 * @param causeValue the cause value of this product message
	 */
	public void setCauseValue(int causeValue);

	/**
	 * Returns the content of this product message.
	 *
	 * @return the content of this product message
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this product message.
	 *
	 * @param content the content of this product message
	 */
	public void setContent(String content);

	/**
	 * Returns the description of this product message.
	 *
	 * @return the description of this product message
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this product message.
	 *
	 * @param description the description of this product message
	 */
	public void setDescription(String description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ProductMessage productMessage);

	public int hashCode();

	public CacheModel<ProductMessage> toCacheModel();

	public ProductMessage toEscapedModel();

	public String toString();

	public String toXmlString();
}