/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cmc.gateway.domain.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProvisioningMessage service. Represents a row in the &quot;GW_ProvisioningMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cmc.gateway.domain.model.impl.ProvisioningMessageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cmc.gateway.domain.model.impl.ProvisioningMessageImpl}.
 * </p>
 *
 * @author Richard Nguyen
 * @see ProvisioningMessage
 * @see com.cmc.gateway.domain.model.impl.ProvisioningMessageImpl
 * @see com.cmc.gateway.domain.model.impl.ProvisioningMessageModelImpl
 * @generated
 */
public interface ProvisioningMessageModel extends BaseModel<ProvisioningMessage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a provisioning message model instance should use the {@link ProvisioningMessage} interface instead.
	 */

	/**
	 * Returns the primary key of this provisioning message.
	 *
	 * @return the primary key of this provisioning message
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this provisioning message.
	 *
	 * @param primaryKey the primary key of this provisioning message
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the message ID of this provisioning message.
	 *
	 * @return the message ID of this provisioning message
	 */
	public long getMessageId();

	/**
	 * Sets the message ID of this provisioning message.
	 *
	 * @param messageId the message ID of this provisioning message
	 */
	public void setMessageId(long messageId);

	/**
	 * Returns the group ID of this provisioning message.
	 *
	 * @return the group ID of this provisioning message
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this provisioning message.
	 *
	 * @param groupId the group ID of this provisioning message
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this provisioning message.
	 *
	 * @return the company ID of this provisioning message
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this provisioning message.
	 *
	 * @param companyId the company ID of this provisioning message
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this provisioning message.
	 *
	 * @return the user ID of this provisioning message
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this provisioning message.
	 *
	 * @param userId the user ID of this provisioning message
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this provisioning message.
	 *
	 * @return the user uuid of this provisioning message
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this provisioning message.
	 *
	 * @param userUuid the user uuid of this provisioning message
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this provisioning message.
	 *
	 * @return the create date of this provisioning message
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this provisioning message.
	 *
	 * @param createDate the create date of this provisioning message
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this provisioning message.
	 *
	 * @return the modified date of this provisioning message
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this provisioning message.
	 *
	 * @param modifiedDate the modified date of this provisioning message
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the provisioning ID of this provisioning message.
	 *
	 * @return the provisioning ID of this provisioning message
	 */
	public long getProvisioningId();

	/**
	 * Sets the provisioning ID of this provisioning message.
	 *
	 * @param provisioningId the provisioning ID of this provisioning message
	 */
	public void setProvisioningId(long provisioningId);

	/**
	 * Returns the response code of this provisioning message.
	 *
	 * @return the response code of this provisioning message
	 */
	@AutoEscape
	public String getResponseCode();

	/**
	 * Sets the response code of this provisioning message.
	 *
	 * @param responseCode the response code of this provisioning message
	 */
	public void setResponseCode(String responseCode);

	/**
	 * Returns the cause of this provisioning message.
	 *
	 * @return the cause of this provisioning message
	 */
	@AutoEscape
	public String getCause();

	/**
	 * Sets the cause of this provisioning message.
	 *
	 * @param cause the cause of this provisioning message
	 */
	public void setCause(String cause);

	/**
	 * Returns the cause value of this provisioning message.
	 *
	 * @return the cause value of this provisioning message
	 */
	public int getCauseValue();

	/**
	 * Sets the cause value of this provisioning message.
	 *
	 * @param causeValue the cause value of this provisioning message
	 */
	public void setCauseValue(int causeValue);

	/**
	 * Returns the description of this provisioning message.
	 *
	 * @return the description of this provisioning message
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this provisioning message.
	 *
	 * @param description the description of this provisioning message
	 */
	public void setDescription(String description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ProvisioningMessage provisioningMessage);

	public int hashCode();

	public CacheModel<ProvisioningMessage> toCacheModel();

	public ProvisioningMessage toEscapedModel();

	public String toString();

	public String toXmlString();
}