/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cmc.gateway.domain.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProvisioningEntry service. Represents a row in the &quot;GW_ProvisioningEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cmc.gateway.domain.model.impl.ProvisioningEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cmc.gateway.domain.model.impl.ProvisioningEntryImpl}.
 * </p>
 *
 * @author Richard Nguyen
 * @see ProvisioningEntry
 * @see com.cmc.gateway.domain.model.impl.ProvisioningEntryImpl
 * @see com.cmc.gateway.domain.model.impl.ProvisioningEntryModelImpl
 * @generated
 */
public interface ProvisioningEntryModel extends BaseModel<ProvisioningEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a provisioning entry model instance should use the {@link ProvisioningEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this provisioning entry.
	 *
	 * @return the primary key of this provisioning entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this provisioning entry.
	 *
	 * @param primaryKey the primary key of this provisioning entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the provisioning ID of this provisioning entry.
	 *
	 * @return the provisioning ID of this provisioning entry
	 */
	public long getProvisioningId();

	/**
	 * Sets the provisioning ID of this provisioning entry.
	 *
	 * @param provisioningId the provisioning ID of this provisioning entry
	 */
	public void setProvisioningId(long provisioningId);

	/**
	 * Returns the group ID of this provisioning entry.
	 *
	 * @return the group ID of this provisioning entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this provisioning entry.
	 *
	 * @param groupId the group ID of this provisioning entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this provisioning entry.
	 *
	 * @return the company ID of this provisioning entry
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this provisioning entry.
	 *
	 * @param companyId the company ID of this provisioning entry
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this provisioning entry.
	 *
	 * @return the user ID of this provisioning entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this provisioning entry.
	 *
	 * @param userId the user ID of this provisioning entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this provisioning entry.
	 *
	 * @return the user uuid of this provisioning entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this provisioning entry.
	 *
	 * @param userUuid the user uuid of this provisioning entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this provisioning entry.
	 *
	 * @return the create date of this provisioning entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this provisioning entry.
	 *
	 * @param createDate the create date of this provisioning entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this provisioning entry.
	 *
	 * @return the modified date of this provisioning entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this provisioning entry.
	 *
	 * @param modifiedDate the modified date of this provisioning entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the provisioning type of this provisioning entry.
	 *
	 * @return the provisioning type of this provisioning entry
	 */
	@AutoEscape
	public String getProvisioningType();

	/**
	 * Sets the provisioning type of this provisioning entry.
	 *
	 * @param provisioningType the provisioning type of this provisioning entry
	 */
	public void setProvisioningType(String provisioningType);

	/**
	 * Returns the code of this provisioning entry.
	 *
	 * @return the code of this provisioning entry
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this provisioning entry.
	 *
	 * @param code the code of this provisioning entry
	 */
	public void setCode(String code);

	/**
	 * Returns the title of this provisioning entry.
	 *
	 * @return the title of this provisioning entry
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this provisioning entry.
	 *
	 * @param title the title of this provisioning entry
	 */
	public void setTitle(String title);

	/**
	 * Returns the connection host of this provisioning entry.
	 *
	 * @return the connection host of this provisioning entry
	 */
	@AutoEscape
	public String getConnectionHost();

	/**
	 * Sets the connection host of this provisioning entry.
	 *
	 * @param connectionHost the connection host of this provisioning entry
	 */
	public void setConnectionHost(String connectionHost);

	/**
	 * Returns the connection port of this provisioning entry.
	 *
	 * @return the connection port of this provisioning entry
	 */
	public int getConnectionPort();

	/**
	 * Sets the connection port of this provisioning entry.
	 *
	 * @param connectionPort the connection port of this provisioning entry
	 */
	public void setConnectionPort(int connectionPort);

	/**
	 * Returns the connect by user name of this provisioning entry.
	 *
	 * @return the connect by user name of this provisioning entry
	 */
	@AutoEscape
	public String getConnectByUserName();

	/**
	 * Sets the connect by user name of this provisioning entry.
	 *
	 * @param connectByUserName the connect by user name of this provisioning entry
	 */
	public void setConnectByUserName(String connectByUserName);

	/**
	 * Returns the connect by password of this provisioning entry.
	 *
	 * @return the connect by password of this provisioning entry
	 */
	@AutoEscape
	public String getConnectByPassword();

	/**
	 * Sets the connect by password of this provisioning entry.
	 *
	 * @param connectByPassword the connect by password of this provisioning entry
	 */
	public void setConnectByPassword(String connectByPassword);

	/**
	 * Returns the process class of this provisioning entry.
	 *
	 * @return the process class of this provisioning entry
	 */
	@AutoEscape
	public String getProcessClass();

	/**
	 * Sets the process class of this provisioning entry.
	 *
	 * @param processClass the process class of this provisioning entry
	 */
	public void setProcessClass(String processClass);

	/**
	 * Returns the process method of this provisioning entry.
	 *
	 * @return the process method of this provisioning entry
	 */
	@AutoEscape
	public String getProcessMethod();

	/**
	 * Sets the process method of this provisioning entry.
	 *
	 * @param processMethod the process method of this provisioning entry
	 */
	public void setProcessMethod(String processMethod);

	/**
	 * Returns the properties of this provisioning entry.
	 *
	 * @return the properties of this provisioning entry
	 */
	@AutoEscape
	public String getProperties();

	/**
	 * Sets the properties of this provisioning entry.
	 *
	 * @param properties the properties of this provisioning entry
	 */
	public void setProperties(String properties);

	/**
	 * Returns the status of this provisioning entry.
	 *
	 * @return the status of this provisioning entry
	 */
	public int getStatus();

	/**
	 * Sets the status of this provisioning entry.
	 *
	 * @param status the status of this provisioning entry
	 */
	public void setStatus(int status);

	/**
	 * Returns the description of this provisioning entry.
	 *
	 * @return the description of this provisioning entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this provisioning entry.
	 *
	 * @param description the description of this provisioning entry
	 */
	public void setDescription(String description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ProvisioningEntry provisioningEntry);

	public int hashCode();

	public CacheModel<ProvisioningEntry> toCacheModel();

	public ProvisioningEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}