/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cmc.gateway.domain.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProvisioningAction service. Represents a row in the &quot;GW_ProvisioningAction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.cmc.gateway.domain.model.impl.ProvisioningActionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.cmc.gateway.domain.model.impl.ProvisioningActionImpl}.
 * </p>
 *
 * @author Richard Nguyen
 * @see ProvisioningAction
 * @see com.cmc.gateway.domain.model.impl.ProvisioningActionImpl
 * @see com.cmc.gateway.domain.model.impl.ProvisioningActionModelImpl
 * @generated
 */
public interface ProvisioningActionModel extends BaseModel<ProvisioningAction> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a provisioning action model instance should use the {@link ProvisioningAction} interface instead.
	 */

	/**
	 * Returns the primary key of this provisioning action.
	 *
	 * @return the primary key of this provisioning action
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this provisioning action.
	 *
	 * @param primaryKey the primary key of this provisioning action
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the action ID of this provisioning action.
	 *
	 * @return the action ID of this provisioning action
	 */
	public long getActionId();

	/**
	 * Sets the action ID of this provisioning action.
	 *
	 * @param actionId the action ID of this provisioning action
	 */
	public void setActionId(long actionId);

	/**
	 * Returns the group ID of this provisioning action.
	 *
	 * @return the group ID of this provisioning action
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this provisioning action.
	 *
	 * @param groupId the group ID of this provisioning action
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this provisioning action.
	 *
	 * @return the company ID of this provisioning action
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this provisioning action.
	 *
	 * @param companyId the company ID of this provisioning action
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this provisioning action.
	 *
	 * @return the user ID of this provisioning action
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this provisioning action.
	 *
	 * @param userId the user ID of this provisioning action
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this provisioning action.
	 *
	 * @return the user uuid of this provisioning action
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this provisioning action.
	 *
	 * @param userUuid the user uuid of this provisioning action
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this provisioning action.
	 *
	 * @return the create date of this provisioning action
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this provisioning action.
	 *
	 * @param createDate the create date of this provisioning action
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this provisioning action.
	 *
	 * @return the modified date of this provisioning action
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this provisioning action.
	 *
	 * @param modifiedDate the modified date of this provisioning action
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the provisioning ID of this provisioning action.
	 *
	 * @return the provisioning ID of this provisioning action
	 */
	public long getProvisioningId();

	/**
	 * Sets the provisioning ID of this provisioning action.
	 *
	 * @param provisioningId the provisioning ID of this provisioning action
	 */
	public void setProvisioningId(long provisioningId);

	/**
	 * Returns the command ID of this provisioning action.
	 *
	 * @return the command ID of this provisioning action
	 */
	public long getCommandId();

	/**
	 * Sets the command ID of this provisioning action.
	 *
	 * @param commandId the command ID of this provisioning action
	 */
	public void setCommandId(long commandId);

	/**
	 * Returns the priority of this provisioning action.
	 *
	 * @return the priority of this provisioning action
	 */
	public int getPriority();

	/**
	 * Sets the priority of this provisioning action.
	 *
	 * @param priority the priority of this provisioning action
	 */
	public void setPriority(int priority);

	/**
	 * Returns the timeout of this provisioning action.
	 *
	 * @return the timeout of this provisioning action
	 */
	public int getTimeout();

	/**
	 * Sets the timeout of this provisioning action.
	 *
	 * @param timeout the timeout of this provisioning action
	 */
	public void setTimeout(int timeout);

	/**
	 * Returns the retry enable of this provisioning action.
	 *
	 * @return the retry enable of this provisioning action
	 */
	public boolean getRetryEnable();

	/**
	 * Returns <code>true</code> if this provisioning action is retry enable.
	 *
	 * @return <code>true</code> if this provisioning action is retry enable; <code>false</code> otherwise
	 */
	public boolean isRetryEnable();

	/**
	 * Sets whether this provisioning action is retry enable.
	 *
	 * @param retryEnable the retry enable of this provisioning action
	 */
	public void setRetryEnable(boolean retryEnable);

	/**
	 * Returns the max retry of this provisioning action.
	 *
	 * @return the max retry of this provisioning action
	 */
	public int getMaxRetry();

	/**
	 * Sets the max retry of this provisioning action.
	 *
	 * @param maxRetry the max retry of this provisioning action
	 */
	public void setMaxRetry(int maxRetry);

	/**
	 * Returns the log enable of this provisioning action.
	 *
	 * @return the log enable of this provisioning action
	 */
	public boolean getLogEnable();

	/**
	 * Returns <code>true</code> if this provisioning action is log enable.
	 *
	 * @return <code>true</code> if this provisioning action is log enable; <code>false</code> otherwise
	 */
	public boolean isLogEnable();

	/**
	 * Sets whether this provisioning action is log enable.
	 *
	 * @param logEnable the log enable of this provisioning action
	 */
	public void setLogEnable(boolean logEnable);

	/**
	 * Returns the process class of this provisioning action.
	 *
	 * @return the process class of this provisioning action
	 */
	@AutoEscape
	public String getProcessClass();

	/**
	 * Sets the process class of this provisioning action.
	 *
	 * @param processClass the process class of this provisioning action
	 */
	public void setProcessClass(String processClass);

	/**
	 * Returns the process method of this provisioning action.
	 *
	 * @return the process method of this provisioning action
	 */
	@AutoEscape
	public String getProcessMethod();

	/**
	 * Sets the process method of this provisioning action.
	 *
	 * @param processMethod the process method of this provisioning action
	 */
	public void setProcessMethod(String processMethod);

	/**
	 * Returns the properties of this provisioning action.
	 *
	 * @return the properties of this provisioning action
	 */
	@AutoEscape
	public String getProperties();

	/**
	 * Sets the properties of this provisioning action.
	 *
	 * @param properties the properties of this provisioning action
	 */
	public void setProperties(String properties);

	/**
	 * Returns the status of this provisioning action.
	 *
	 * @return the status of this provisioning action
	 */
	public int getStatus();

	/**
	 * Sets the status of this provisioning action.
	 *
	 * @param status the status of this provisioning action
	 */
	public void setStatus(int status);

	/**
	 * Returns the description of this provisioning action.
	 *
	 * @return the description of this provisioning action
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this provisioning action.
	 *
	 * @param description the description of this provisioning action
	 */
	public void setDescription(String description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ProvisioningAction provisioningAction);

	public int hashCode();

	public CacheModel<ProvisioningAction> toCacheModel();

	public ProvisioningAction toEscapedModel();

	public String toString();

	public String toXmlString();
}