/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cmc.gateway.domain.model.impl;

import com.cmc.gateway.domain.model.CommandEntry;
import com.cmc.gateway.domain.service.CommandEntryLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the CommandEntry service. Represents a row in the &quot;GW_CommandEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommandEntryImpl}.
 * </p>
 *
 * @author Richard Nguyen
 * @see CommandEntryImpl
 * @see com.cmc.gateway.domain.model.CommandEntry
 * @generated
 */
public abstract class CommandEntryBaseImpl extends CommandEntryModelImpl
	implements CommandEntry {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a command entry model instance should use the {@link CommandEntry} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			CommandEntryLocalServiceUtil.addCommandEntry(this);
		}
		else {
			CommandEntryLocalServiceUtil.updateCommandEntry(this);
		}
	}
}