/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cmc.gateway.domain.model.impl;

import com.cmc.gateway.domain.model.ProductMessage;
import com.cmc.gateway.domain.model.ProductMessageModel;
import com.cmc.gateway.domain.model.ProductMessageSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ProductMessage service. Represents a row in the &quot;GW_ProductMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.cmc.gateway.domain.model.ProductMessageModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProductMessageImpl}.
 * </p>
 *
 * @author Richard Nguyen
 * @see ProductMessageImpl
 * @see com.cmc.gateway.domain.model.ProductMessage
 * @see com.cmc.gateway.domain.model.ProductMessageModel
 * @generated
 */
@JSON(strict = true)
public class ProductMessageModelImpl extends BaseModelImpl<ProductMessage>
	implements ProductMessageModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a product message model instance should use the {@link com.cmc.gateway.domain.model.ProductMessage} interface instead.
	 */
	public static final String TABLE_NAME = "GW_ProductMessage";
	public static final Object[][] TABLE_COLUMNS = {
			{ "messageId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "productId", Types.BIGINT },
			{ "actionType", Types.VARCHAR },
			{ "channel", Types.VARCHAR },
			{ "cause", Types.VARCHAR },
			{ "languageId", Types.VARCHAR },
			{ "causeValue", Types.INTEGER },
			{ "content", Types.VARCHAR },
			{ "description", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table GW_ProductMessage (messageId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,productId LONG,actionType VARCHAR(75) null,channel VARCHAR(75) null,cause VARCHAR(75) null,languageId VARCHAR(75) null,causeValue INTEGER,content STRING null,description STRING null)";
	public static final String TABLE_SQL_DROP = "drop table GW_ProductMessage";
	public static final String ORDER_BY_JPQL = " ORDER BY productMessage.productId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY GW_ProductMessage.productId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.cmc.gateway.domain.model.ProductMessage"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.cmc.gateway.domain.model.ProductMessage"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.cmc.gateway.domain.model.ProductMessage"),
			true);
	public static long ACTIONTYPE_COLUMN_BITMASK = 1L;
	public static long CHANNEL_COLUMN_BITMASK = 2L;
	public static long PRODUCTID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ProductMessage toModel(ProductMessageSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ProductMessage model = new ProductMessageImpl();

		model.setMessageId(soapModel.getMessageId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setProductId(soapModel.getProductId());
		model.setActionType(soapModel.getActionType());
		model.setChannel(soapModel.getChannel());
		model.setCause(soapModel.getCause());
		model.setLanguageId(soapModel.getLanguageId());
		model.setCauseValue(soapModel.getCauseValue());
		model.setContent(soapModel.getContent());
		model.setDescription(soapModel.getDescription());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ProductMessage> toModels(ProductMessageSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ProductMessage> models = new ArrayList<ProductMessage>(soapModels.length);

		for (ProductMessageSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.cmc.gateway.domain.model.ProductMessage"));

	public ProductMessageModelImpl() {
	}

	public long getPrimaryKey() {
		return _messageId;
	}

	public void setPrimaryKey(long primaryKey) {
		setMessageId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_messageId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return ProductMessage.class;
	}

	public String getModelClassName() {
		return ProductMessage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("messageId", getMessageId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("productId", getProductId());
		attributes.put("actionType", getActionType());
		attributes.put("channel", getChannel());
		attributes.put("cause", getCause());
		attributes.put("languageId", getLanguageId());
		attributes.put("causeValue", getCauseValue());
		attributes.put("content", getContent());
		attributes.put("description", getDescription());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long messageId = (Long)attributes.get("messageId");

		if (messageId != null) {
			setMessageId(messageId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long productId = (Long)attributes.get("productId");

		if (productId != null) {
			setProductId(productId);
		}

		String actionType = (String)attributes.get("actionType");

		if (actionType != null) {
			setActionType(actionType);
		}

		String channel = (String)attributes.get("channel");

		if (channel != null) {
			setChannel(channel);
		}

		String cause = (String)attributes.get("cause");

		if (cause != null) {
			setCause(cause);
		}

		String languageId = (String)attributes.get("languageId");

		if (languageId != null) {
			setLanguageId(languageId);
		}

		Integer causeValue = (Integer)attributes.get("causeValue");

		if (causeValue != null) {
			setCauseValue(causeValue);
		}

		String content = (String)attributes.get("content");

		if (content != null) {
			setContent(content);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}
	}

	@JSON
	public long getMessageId() {
		return _messageId;
	}

	public void setMessageId(long messageId) {
		_messageId = messageId;
	}

	@JSON
	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	public long getProductId() {
		return _productId;
	}

	public void setProductId(long productId) {
		_columnBitmask = -1L;

		if (!_setOriginalProductId) {
			_setOriginalProductId = true;

			_originalProductId = _productId;
		}

		_productId = productId;
	}

	public long getOriginalProductId() {
		return _originalProductId;
	}

	@JSON
	public String getActionType() {
		if (_actionType == null) {
			return StringPool.BLANK;
		}
		else {
			return _actionType;
		}
	}

	public void setActionType(String actionType) {
		_columnBitmask |= ACTIONTYPE_COLUMN_BITMASK;

		if (_originalActionType == null) {
			_originalActionType = _actionType;
		}

		_actionType = actionType;
	}

	public String getOriginalActionType() {
		return GetterUtil.getString(_originalActionType);
	}

	@JSON
	public String getChannel() {
		if (_channel == null) {
			return StringPool.BLANK;
		}
		else {
			return _channel;
		}
	}

	public void setChannel(String channel) {
		_columnBitmask |= CHANNEL_COLUMN_BITMASK;

		if (_originalChannel == null) {
			_originalChannel = _channel;
		}

		_channel = channel;
	}

	public String getOriginalChannel() {
		return GetterUtil.getString(_originalChannel);
	}

	@JSON
	public String getCause() {
		if (_cause == null) {
			return StringPool.BLANK;
		}
		else {
			return _cause;
		}
	}

	public void setCause(String cause) {
		_cause = cause;
	}

	@JSON
	public String getLanguageId() {
		if (_languageId == null) {
			return StringPool.BLANK;
		}
		else {
			return _languageId;
		}
	}

	public void setLanguageId(String languageId) {
		_languageId = languageId;
	}

	@JSON
	public int getCauseValue() {
		return _causeValue;
	}

	public void setCauseValue(int causeValue) {
		_causeValue = causeValue;
	}

	@JSON
	public String getContent() {
		if (_content == null) {
			return StringPool.BLANK;
		}
		else {
			return _content;
		}
	}

	public void setContent(String content) {
		_content = content;
	}

	@JSON
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public void setDescription(String description) {
		_description = description;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ProductMessage.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProductMessage toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (ProductMessage)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		ProductMessageImpl productMessageImpl = new ProductMessageImpl();

		productMessageImpl.setMessageId(getMessageId());
		productMessageImpl.setGroupId(getGroupId());
		productMessageImpl.setCompanyId(getCompanyId());
		productMessageImpl.setUserId(getUserId());
		productMessageImpl.setCreateDate(getCreateDate());
		productMessageImpl.setModifiedDate(getModifiedDate());
		productMessageImpl.setProductId(getProductId());
		productMessageImpl.setActionType(getActionType());
		productMessageImpl.setChannel(getChannel());
		productMessageImpl.setCause(getCause());
		productMessageImpl.setLanguageId(getLanguageId());
		productMessageImpl.setCauseValue(getCauseValue());
		productMessageImpl.setContent(getContent());
		productMessageImpl.setDescription(getDescription());

		productMessageImpl.resetOriginalValues();

		return productMessageImpl;
	}

	public int compareTo(ProductMessage productMessage) {
		int value = 0;

		if (getProductId() < productMessage.getProductId()) {
			value = -1;
		}
		else if (getProductId() > productMessage.getProductId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		ProductMessage productMessage = null;

		try {
			productMessage = (ProductMessage)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = productMessage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ProductMessageModelImpl productMessageModelImpl = this;

		productMessageModelImpl._originalProductId = productMessageModelImpl._productId;

		productMessageModelImpl._setOriginalProductId = false;

		productMessageModelImpl._originalActionType = productMessageModelImpl._actionType;

		productMessageModelImpl._originalChannel = productMessageModelImpl._channel;

		productMessageModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ProductMessage> toCacheModel() {
		ProductMessageCacheModel productMessageCacheModel = new ProductMessageCacheModel();

		productMessageCacheModel.messageId = getMessageId();

		productMessageCacheModel.groupId = getGroupId();

		productMessageCacheModel.companyId = getCompanyId();

		productMessageCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			productMessageCacheModel.createDate = createDate.getTime();
		}
		else {
			productMessageCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			productMessageCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			productMessageCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		productMessageCacheModel.productId = getProductId();

		productMessageCacheModel.actionType = getActionType();

		String actionType = productMessageCacheModel.actionType;

		if ((actionType != null) && (actionType.length() == 0)) {
			productMessageCacheModel.actionType = null;
		}

		productMessageCacheModel.channel = getChannel();

		String channel = productMessageCacheModel.channel;

		if ((channel != null) && (channel.length() == 0)) {
			productMessageCacheModel.channel = null;
		}

		productMessageCacheModel.cause = getCause();

		String cause = productMessageCacheModel.cause;

		if ((cause != null) && (cause.length() == 0)) {
			productMessageCacheModel.cause = null;
		}

		productMessageCacheModel.languageId = getLanguageId();

		String languageId = productMessageCacheModel.languageId;

		if ((languageId != null) && (languageId.length() == 0)) {
			productMessageCacheModel.languageId = null;
		}

		productMessageCacheModel.causeValue = getCauseValue();

		productMessageCacheModel.content = getContent();

		String content = productMessageCacheModel.content;

		if ((content != null) && (content.length() == 0)) {
			productMessageCacheModel.content = null;
		}

		productMessageCacheModel.description = getDescription();

		String description = productMessageCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			productMessageCacheModel.description = null;
		}

		return productMessageCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{messageId=");
		sb.append(getMessageId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", productId=");
		sb.append(getProductId());
		sb.append(", actionType=");
		sb.append(getActionType());
		sb.append(", channel=");
		sb.append(getChannel());
		sb.append(", cause=");
		sb.append(getCause());
		sb.append(", languageId=");
		sb.append(getLanguageId());
		sb.append(", causeValue=");
		sb.append(getCauseValue());
		sb.append(", content=");
		sb.append(getContent());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("com.cmc.gateway.domain.model.ProductMessage");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>messageId</column-name><column-value><![CDATA[");
		sb.append(getMessageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>productId</column-name><column-value><![CDATA[");
		sb.append(getProductId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>actionType</column-name><column-value><![CDATA[");
		sb.append(getActionType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>channel</column-name><column-value><![CDATA[");
		sb.append(getChannel());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cause</column-name><column-value><![CDATA[");
		sb.append(getCause());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>languageId</column-name><column-value><![CDATA[");
		sb.append(getLanguageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>causeValue</column-name><column-value><![CDATA[");
		sb.append(getCauseValue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>content</column-name><column-value><![CDATA[");
		sb.append(getContent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ProductMessage.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			ProductMessage.class
		};
	private long _messageId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private long _productId;
	private long _originalProductId;
	private boolean _setOriginalProductId;
	private String _actionType;
	private String _originalActionType;
	private String _channel;
	private String _originalChannel;
	private String _cause;
	private String _languageId;
	private int _causeValue;
	private String _content;
	private String _description;
	private long _columnBitmask;
	private ProductMessage _escapedModelProxy;
}