/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cmc.gateway.domain.model.impl;

import com.cmc.gateway.domain.model.ProvisioningRoute;
import com.cmc.gateway.domain.model.ProvisioningRouteModel;
import com.cmc.gateway.domain.model.ProvisioningRouteSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the ProvisioningRoute service. Represents a row in the &quot;GW_ProvisioningRoute&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.cmc.gateway.domain.model.ProvisioningRouteModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProvisioningRouteImpl}.
 * </p>
 *
 * @author Richard Nguyen
 * @see ProvisioningRouteImpl
 * @see com.cmc.gateway.domain.model.ProvisioningRoute
 * @see com.cmc.gateway.domain.model.ProvisioningRouteModel
 * @generated
 */
@JSON(strict = true)
public class ProvisioningRouteModelImpl extends BaseModelImpl<ProvisioningRoute>
	implements ProvisioningRouteModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a provisioning route model instance should use the {@link com.cmc.gateway.domain.model.ProvisioningRoute} interface instead.
	 */
	public static final String TABLE_NAME = "GW_ProvisioningRoute";
	public static final Object[][] TABLE_COLUMNS = {
			{ "routeId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "provisioningId", Types.BIGINT },
			{ "provisioningType", Types.VARCHAR },
			{ "routeType", Types.VARCHAR },
			{ "routeKey", Types.VARCHAR },
			{ "description", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table GW_ProvisioningRoute (routeId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,provisioningId LONG,provisioningType VARCHAR(75) null,routeType VARCHAR(75) null,routeKey VARCHAR(75) null,description STRING null)";
	public static final String TABLE_SQL_DROP = "drop table GW_ProvisioningRoute";
	public static final String ORDER_BY_JPQL = " ORDER BY provisioningRoute.provisioningId ASC, provisioningRoute.routeType ASC, provisioningRoute.routeKey ASC";
	public static final String ORDER_BY_SQL = " ORDER BY GW_ProvisioningRoute.provisioningId ASC, GW_ProvisioningRoute.routeType ASC, GW_ProvisioningRoute.routeKey ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.cmc.gateway.domain.model.ProvisioningRoute"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.cmc.gateway.domain.model.ProvisioningRoute"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.cmc.gateway.domain.model.ProvisioningRoute"),
			true);
	public static long PROVISIONINGID_COLUMN_BITMASK = 1L;
	public static long PROVISIONINGTYPE_COLUMN_BITMASK = 2L;
	public static long ROUTEKEY_COLUMN_BITMASK = 4L;
	public static long ROUTETYPE_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ProvisioningRoute toModel(ProvisioningRouteSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ProvisioningRoute model = new ProvisioningRouteImpl();

		model.setRouteId(soapModel.getRouteId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setProvisioningId(soapModel.getProvisioningId());
		model.setProvisioningType(soapModel.getProvisioningType());
		model.setRouteType(soapModel.getRouteType());
		model.setRouteKey(soapModel.getRouteKey());
		model.setDescription(soapModel.getDescription());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ProvisioningRoute> toModels(
		ProvisioningRouteSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ProvisioningRoute> models = new ArrayList<ProvisioningRoute>(soapModels.length);

		for (ProvisioningRouteSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.cmc.gateway.domain.model.ProvisioningRoute"));

	public ProvisioningRouteModelImpl() {
	}

	public long getPrimaryKey() {
		return _routeId;
	}

	public void setPrimaryKey(long primaryKey) {
		setRouteId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_routeId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return ProvisioningRoute.class;
	}

	public String getModelClassName() {
		return ProvisioningRoute.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("routeId", getRouteId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("provisioningId", getProvisioningId());
		attributes.put("provisioningType", getProvisioningType());
		attributes.put("routeType", getRouteType());
		attributes.put("routeKey", getRouteKey());
		attributes.put("description", getDescription());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long routeId = (Long)attributes.get("routeId");

		if (routeId != null) {
			setRouteId(routeId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long provisioningId = (Long)attributes.get("provisioningId");

		if (provisioningId != null) {
			setProvisioningId(provisioningId);
		}

		String provisioningType = (String)attributes.get("provisioningType");

		if (provisioningType != null) {
			setProvisioningType(provisioningType);
		}

		String routeType = (String)attributes.get("routeType");

		if (routeType != null) {
			setRouteType(routeType);
		}

		String routeKey = (String)attributes.get("routeKey");

		if (routeKey != null) {
			setRouteKey(routeKey);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}
	}

	@JSON
	public long getRouteId() {
		return _routeId;
	}

	public void setRouteId(long routeId) {
		_routeId = routeId;
	}

	@JSON
	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	public long getProvisioningId() {
		return _provisioningId;
	}

	public void setProvisioningId(long provisioningId) {
		_columnBitmask = -1L;

		if (!_setOriginalProvisioningId) {
			_setOriginalProvisioningId = true;

			_originalProvisioningId = _provisioningId;
		}

		_provisioningId = provisioningId;
	}

	public long getOriginalProvisioningId() {
		return _originalProvisioningId;
	}

	@JSON
	public String getProvisioningType() {
		if (_provisioningType == null) {
			return StringPool.BLANK;
		}
		else {
			return _provisioningType;
		}
	}

	public void setProvisioningType(String provisioningType) {
		_columnBitmask |= PROVISIONINGTYPE_COLUMN_BITMASK;

		if (_originalProvisioningType == null) {
			_originalProvisioningType = _provisioningType;
		}

		_provisioningType = provisioningType;
	}

	public String getOriginalProvisioningType() {
		return GetterUtil.getString(_originalProvisioningType);
	}

	@JSON
	public String getRouteType() {
		if (_routeType == null) {
			return StringPool.BLANK;
		}
		else {
			return _routeType;
		}
	}

	public void setRouteType(String routeType) {
		_columnBitmask = -1L;

		if (_originalRouteType == null) {
			_originalRouteType = _routeType;
		}

		_routeType = routeType;
	}

	public String getOriginalRouteType() {
		return GetterUtil.getString(_originalRouteType);
	}

	@JSON
	public String getRouteKey() {
		if (_routeKey == null) {
			return StringPool.BLANK;
		}
		else {
			return _routeKey;
		}
	}

	public void setRouteKey(String routeKey) {
		_columnBitmask = -1L;

		if (_originalRouteKey == null) {
			_originalRouteKey = _routeKey;
		}

		_routeKey = routeKey;
	}

	public String getOriginalRouteKey() {
		return GetterUtil.getString(_originalRouteKey);
	}

	@JSON
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public void setDescription(String description) {
		_description = description;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			ProvisioningRoute.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProvisioningRoute toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (ProvisioningRoute)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		ProvisioningRouteImpl provisioningRouteImpl = new ProvisioningRouteImpl();

		provisioningRouteImpl.setRouteId(getRouteId());
		provisioningRouteImpl.setGroupId(getGroupId());
		provisioningRouteImpl.setCompanyId(getCompanyId());
		provisioningRouteImpl.setUserId(getUserId());
		provisioningRouteImpl.setCreateDate(getCreateDate());
		provisioningRouteImpl.setModifiedDate(getModifiedDate());
		provisioningRouteImpl.setProvisioningId(getProvisioningId());
		provisioningRouteImpl.setProvisioningType(getProvisioningType());
		provisioningRouteImpl.setRouteType(getRouteType());
		provisioningRouteImpl.setRouteKey(getRouteKey());
		provisioningRouteImpl.setDescription(getDescription());

		provisioningRouteImpl.resetOriginalValues();

		return provisioningRouteImpl;
	}

	public int compareTo(ProvisioningRoute provisioningRoute) {
		int value = 0;

		if (getProvisioningId() < provisioningRoute.getProvisioningId()) {
			value = -1;
		}
		else if (getProvisioningId() > provisioningRoute.getProvisioningId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = getRouteType().compareTo(provisioningRoute.getRouteType());

		if (value != 0) {
			return value;
		}

		value = getRouteKey().compareTo(provisioningRoute.getRouteKey());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		ProvisioningRoute provisioningRoute = null;

		try {
			provisioningRoute = (ProvisioningRoute)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = provisioningRoute.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ProvisioningRouteModelImpl provisioningRouteModelImpl = this;

		provisioningRouteModelImpl._originalProvisioningId = provisioningRouteModelImpl._provisioningId;

		provisioningRouteModelImpl._setOriginalProvisioningId = false;

		provisioningRouteModelImpl._originalProvisioningType = provisioningRouteModelImpl._provisioningType;

		provisioningRouteModelImpl._originalRouteType = provisioningRouteModelImpl._routeType;

		provisioningRouteModelImpl._originalRouteKey = provisioningRouteModelImpl._routeKey;

		provisioningRouteModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ProvisioningRoute> toCacheModel() {
		ProvisioningRouteCacheModel provisioningRouteCacheModel = new ProvisioningRouteCacheModel();

		provisioningRouteCacheModel.routeId = getRouteId();

		provisioningRouteCacheModel.groupId = getGroupId();

		provisioningRouteCacheModel.companyId = getCompanyId();

		provisioningRouteCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			provisioningRouteCacheModel.createDate = createDate.getTime();
		}
		else {
			provisioningRouteCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			provisioningRouteCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			provisioningRouteCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		provisioningRouteCacheModel.provisioningId = getProvisioningId();

		provisioningRouteCacheModel.provisioningType = getProvisioningType();

		String provisioningType = provisioningRouteCacheModel.provisioningType;

		if ((provisioningType != null) && (provisioningType.length() == 0)) {
			provisioningRouteCacheModel.provisioningType = null;
		}

		provisioningRouteCacheModel.routeType = getRouteType();

		String routeType = provisioningRouteCacheModel.routeType;

		if ((routeType != null) && (routeType.length() == 0)) {
			provisioningRouteCacheModel.routeType = null;
		}

		provisioningRouteCacheModel.routeKey = getRouteKey();

		String routeKey = provisioningRouteCacheModel.routeKey;

		if ((routeKey != null) && (routeKey.length() == 0)) {
			provisioningRouteCacheModel.routeKey = null;
		}

		provisioningRouteCacheModel.description = getDescription();

		String description = provisioningRouteCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			provisioningRouteCacheModel.description = null;
		}

		return provisioningRouteCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{routeId=");
		sb.append(getRouteId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", provisioningId=");
		sb.append(getProvisioningId());
		sb.append(", provisioningType=");
		sb.append(getProvisioningType());
		sb.append(", routeType=");
		sb.append(getRouteType());
		sb.append(", routeKey=");
		sb.append(getRouteKey());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.cmc.gateway.domain.model.ProvisioningRoute");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>routeId</column-name><column-value><![CDATA[");
		sb.append(getRouteId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>provisioningId</column-name><column-value><![CDATA[");
		sb.append(getProvisioningId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>provisioningType</column-name><column-value><![CDATA[");
		sb.append(getProvisioningType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>routeType</column-name><column-value><![CDATA[");
		sb.append(getRouteType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>routeKey</column-name><column-value><![CDATA[");
		sb.append(getRouteKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ProvisioningRoute.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			ProvisioningRoute.class
		};
	private long _routeId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private long _provisioningId;
	private long _originalProvisioningId;
	private boolean _setOriginalProvisioningId;
	private String _provisioningType;
	private String _originalProvisioningType;
	private String _routeType;
	private String _originalRouteType;
	private String _routeKey;
	private String _originalRouteKey;
	private String _description;
	private long _columnBitmask;
	private ProvisioningRoute _escapedModelProxy;
}